CREATE DATABASE SMOOTHIEBIZDB;
USE SMOOTHIEBIZDB;

CREATE TABLE NUTRITION_VALUE (
ID INT AUTO_INCREMENT PRIMARY KEY, 
CARBOHYDRATE DOUBLE,
PROTEIN DOUBLE,
FAT DOUBLE,
CHOLESTROL DOUBLE,
SODIUM DOUBLE,
POTASSIUM DOUBLE,
CALCIUM DOUBLE,
IRON DOUBLE,
CALORIES DOUBLE);

CREATE TABLE PRODUCT (
ID INT AUTO_INCREMENT PRIMARY KEY, 
NAME VARCHAR(255) NOT NULL, 
DESCRIPTION VARCHAR(500), 
PRICE DOUBLE,
NUTRITION_VALUE_ID INT,
CONSTRAINT FK_NUTRITIONVALUE FOREIGN KEY (NUTRITION_VALUE_ID) REFERENCES NUTRITION_VALUE(ID));

CREATE TABLE ORDERS (
ID INT AUTO_INCREMENT PRIMARY KEY,
DATE_CREATED DATE, 
STATUS VARCHAR(255));

CREATE TABLE ORDER_PRODUCT (
QUANTITY INT NOT NULL, 
ORDER_ID INT NOT NULL, 
PRODUCT_ID INT NOT NULL, 
PRIMARY KEY (ORDER_ID, PRODUCT_ID),
CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID));

CREATE TABLE APP_USER (
ID INT AUTO_INCREMENT PRIMARY KEY, 
EMAIL VARCHAR(255), 
PASSWORD VARCHAR(255), 
ROLE VARCHAR(255), 
USER_NAME VARCHAR(255));


INSERT INTO PRODUCT (NAME, PRICE) VALUES
('CARROT MANGO', 2.5),
('STRAWBERRY COCONUT', 3.75),
('BANANA BLUEBERRY', 5.25),
('ALMOND ORANGE', 2),
('PINEAPPLE', 1.35);

INSERT INTO APP_USER (USER_NAME, PASSWORD, ROLE) VALUES
('Alex','owner','owner'),
('Bob','user','user');