spring:
  datasource:
    name: smoothiebizdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smoothiebizdb
    username: root
    password: admin
  jpa:
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: dev